### PR TITLE
Add chromedriver as npm module

### LINKED ISSUE #21: Add chromedriver to package.json
@gedex is there a reason why `chromedrive` is a prerequisite that needs to be installed separately instead of being a dependency that is included in the `package.json` file? If we add it to `package.json` we can control the version that is used and don't need to worry about people installing an incompatible version.

### PR DESCRIPTION
**Pull request by rodrigoprimo**
This way it is not necessary to install chromedriver separately.

Inspired by https://github.com/Automattic/wp-e2e-tests/pull/774

Fixes #21

### CODE REVIEW

**Comment by rodrigoprimo** [comment]
@gedex, any suggestion on how to fix the failing Travis build (https://travis-ci.org/woocommerce/wp-e2e-webdriver/builds/298049163#L999). `eslint` is complaining that `chromedriver` is defined but never used, which is true but seems to be necessary to add `chromedriver` to the path (see https://github.com/Automattic/wp-e2e-tests/pull/774/commits/e59c053090da110bdd5aa3d60a135b52cb327e16 cc @bsessions85).

**Comment by bsessions85** [comment]
@rodrigoprimo Could you use something like `import chromedriver from 'chromedriver'; // eslint-disable-line no-unused-vars`?

**Comment by gedex** [comment]
Yep, what @bsessions85 suggested above works fine. Got no complain with that:

```
$ npm run lint

> wp-e2e-webdriver@0.11.0 lint /Users/gedex/Works/Automattic/wp-e2e-webdriver
> eslint src test
```

**Comment by gedex** [comment]
Couple notes:

* Need to lock down dependency versions too when package.json is updated? It's a been a while, so I vaguely remember. @bsessions85 can you confirm we just need to run `npm shrinkwrap`?
* We still do `apt-get install chromium-chromedriver` in `.travis.yml` so not sure which `chomedriver` is used by the build container. Not a biggie as long it passes the tests.

**Comment by gedex** [comment]
Ignore the `npm shrinkwrap` is should be ran automatically when we do `npm version`.

**Review by gedex — APPROVED** [review]

**Comment by bsessions85** [comment]
I would remove the apt-get install chromium-chromedriver in .travis.yml so that you always know which version of Chromedriver you're getting. It could help with debugging if there is an issue related to a specific version.

**Comment by rodrigoprimo** [comment]
Thanks for your suggestions. I added `// eslint-disable-line no-unused-vars` to the line that imports `chromedriver` and removed the command to install `chromedriver` using `apt-get` in the Travis build container.

I also removed from `.travis.xml` the command `apt-get update` (see https://github.com/woocommerce/wp-e2e-webdriver/pull/24/commits/501372116824eacaf96c16e0cf7720e355545739) as I assumed its only purpose was to update the package index before installing `chromium-chromedriver`, please let me know if that is not the case and `apt-get update` is still needed for something else.

**Pull request merged**
